### ISSUE TITLE
fast streaming `NULL` data when radiometer LCB is isolated

### ISSUE THREAD

**Issue by bluesquall** [whoidsl-mesobot/radiometer-lcmd#5]
I’ve seen this before, and thought there was already a ticket, but I don't see it. 

Today the dæmon flooded LCM with messages on RAD1r while the LCB was isolated. I do not recall whether we had the radiometer running before it was isolated or not.

Try to replicate, then fix.

This may be something to do with the driver for the USB-RS232 converter, since the dæmon should only try to read when the file descriptor indicates there are bytes to read.

**Comment by bluesquall** [comment]
- [ ] Add more details from yesterday's testing later today.
- [x] Prototyped fix last night. 
- [x] Test fix today.
- [ ] Consider whether a larger ringbuffer on the input would have avoided the race condition.
  - Would it be a more robust long-term solution?
  - How much more would it cost in terms of runtime memory? (I’m guessing it would be negligible compared to the rest of the dæmon, even if we eventually need to port to a more resource-constrained platform like the mb3.)
  - Will it be able to perform at 20 Hz and handle synchronization with the streaming radiometer?

**Comment by mesobot-ow** [comment]
#6
